### ISSUE TITLE
Tried to connect as a Java Edition player! Is Floodgate configured correctly?

### ISSUE THREAD

**Issue by byMarioMC** [GeyserMC/Floodgate#475]
Hello! I have Geyser and Floodgate in my Aternos server, but when a bedrock player tries to enter, he can't. Last time I opened the server, bedrock players could join, but now they can't. I didn't touch anything.
**Console log:**
[01:02:27] [epollEventLoopGroup-3-1/INFO]: [Geyser-Spigot] /##.##.###.###:##### tried to connect!
[01:02:28] [epollEventLoopGroup-3-3/INFO]: [Geyser-Spigot] Player connected with username ToryFrndz08
[01:02:28] [defaultEventLoopGroup-6-3/INFO]: [Geyser-Spigot] ToryFrndz08 (logged in as: ToryFrndz08) has connected to the Java server
[01:02:28] [defaultEventLoopGroup-6-3/INFO]: [Geyser-Spigot] ToryFrndz08 has disconnected from the Java server because of Tried to connect as a Java Edition player! Is Floodgate configured correctly?
[01:02:28] [defaultEventLoopGroup-6-3/WARN]: [Geyser-Spigot] Cannot reply to ClientboundHelloPacket without profile and access token.
[01:02:28] [Server thread/INFO]: ToryFrndz08 (/##.##.###.###:#) lost connection: Disconnected

Maybe is something about "ClientboundHelloPacket"? 
I've censored the IPs because I don't know if it's dangerous for him. If some information is missing, tell me. Thanks!

**Comment by Konicai** [comment]
This issue was tracked in #474 and was fixed 4hr ago. Try uninstalling and reinstalling floodgate. Aternos may have not updated the jar yet though, in which case you're waiting for them.

**Comment by byMarioMC** [comment]
Okay... but when I search FloodGate on aternos, it doesn't appear. Do you know why? 
![floodgatereport](https://github.com/GeyserMC/Floodgate/assets/117780465/c8575430-7621-47a3-a46f-85e5338fe2a2)

**Comment by Konicai** [comment]
Then uninstall and reinstall Geyser

**Comment by jefflima1** [comment]
Hello, I know this topic is closed, as resolved, but this problem still happens, using the latest versions of geyser and floodgate, it happens very often the player connects and is recognized as a java user, after a few attempts, it is recognized normally through floodgate, I use the recent versions of geyser, floodgate, and papermc, I don't know how to solve it, I've already searched a lot about this problem, and I always get this error, here's a small log about the problem.

  [qui. 13:39:04 INFO  Geyser-Spigot] Jogador conectado com o nome de usuário Vencedor63
  [qui. 13:39:04 INFO  Geyser-Spigot] Vencedor63 (logado como: Vencedor63) conectou-se ao servidor Java
  [qui. 13:39:04 INFO  Geyser-Spigot] Vencedor63 se desconectou do servidor Java: Tentou fazer login como um jogador Java Edition! O Floodgate está configurado corretamente?
! [qui. 13:39:04 WARN  Geyser-Spigot] Cannot reply to ClientboundHelloPacket without profile and access token.
